"""fix exchange request ondelete constraints

Revision ID: acfd19b9d18a
Revises: 
Create Date: 2026-05-06 19:27:46.671692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfd19b9d18a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('offered_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('title_normalized', sa.String(length=200), nullable=True),
    sa.Column('author_normalized', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('cover_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offered_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offered_book_author_normalized'), ['author_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_offered_book_title_normalized'), ['title_normalized'], unique=False)

    op.create_table('user_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'area', name='unique_user_area')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('alternate_contact', sa.String(length=200), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wanted_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('title_normalized', sa.String(length=200), nullable=True),
    sa.Column('author_normalized', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wanted_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wanted_book_author_normalized'), ['author_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_wanted_book_title_normalized'), ['title_normalized'], unique=False)

    op.create_table('exchange_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('offered_book_id', sa.Integer(), nullable=True),
    sa.Column('book_title', sa.String(length=200), nullable=False),
    sa.Column('book_author', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offered_book_id'], ['offered_book.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offered_book_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offered_book_id'], ['offered_book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'offered_book_id', name='unique_user_book_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('exchange_request')
    with op.batch_alter_table('wanted_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wanted_book_title_normalized'))
        batch_op.drop_index(batch_op.f('ix_wanted_book_author_normalized'))

    op.drop_table('wanted_book')
    op.drop_table('user_profile')
    op.drop_table('user_location')
    with op.batch_alter_table('offered_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offered_book_title_normalized'))
        batch_op.drop_index(batch_op.f('ix_offered_book_author_normalized'))

    op.drop_table('offered_book')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
